---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: test1
rules:
  # this is for the 00-presync-create-cert-cm-job
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test1
subjects:
  - kind: ServiceAccount
    name: test1
    namespace: team1-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test1
  namespace: team1-dev
---
apiVersion: batch/v1
kind: Job
metadata:
  name: test1
  namespace: team1-dev
spec:
  template:
    spec:
      containers:
        - resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
          image: registry.redhat.io/openshift4/ose-cli:v4.4
          command:
            - /bin/bash
            - -c
            - |
              oc get secret -A
          imagePullPolicy: Always
          name: presync-create-cert-cm-job
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: test1
      serviceAccountName: test1
      terminationGracePeriodSeconds: 30