kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: team1-admin
users:
  - team1-admin
---
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: team1-dev
users:
  - team1-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitop-create-application
rules:
  - apiGroups:
    - "argoproj.io"
    resources:
    - "applications"
    verbs:
    - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitop-create-application-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitop-create-application
subjects:
  - kind: Group
    name: team1-dev
